### ISSUE TITLE
[1주차 아이템 변경 요청] To bbubbush -> From Ssinsa

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#1]
[변경 전]
bbubbush :: Item02 생성자에 매개변수가 많다면 빌더를 고려하라
Ssinsa :: Item03 private 생성자나 열거타입으로 싱글턴임을 보증하라

[변경 후]
bbubbush :: Item03 private 생성자나 열거타입으로 싱글턴임을 보증하라
Ssinsa :: Item02 생성자에 매개변수가 많다면 빌더를 고려하라

[변경사유]
세번째 아이템이 더 재밌어 보여서 변경을 요청합니다. 수락해주세요 : )

**Comment by SSinsa** [comment]
[답변] 아주 흔쾌히 수락합니다. 빌더 잘해보겠습니다.
