### ISSUE TITLE
(이펙티브 자바) 아이템 03. private 생성자나 열거타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by mike6321** [FourTeamProject/Charmander_EffectiveJava#13]
하나의 페이지 많은 내용이 있으나 단락별로 구분이 모호해서 읽기가 조금 버거운 느낌이 있습니다!
단락별로 구분을 해보는것이 어떠한가요~?
ex) 들어가면서 부분을 각주로 묶는방법!

자바의 싱글턴과 스프링의 싱글턴에 대한 명확한 차이점에 대한 내용이 있었으면 조금 더 알찬 내용이 되지 않을까 싶네요!

**Comment by bbubbush** [comment]
리뷰 감사합니다 준우님. 요청사항을 아래와 같이 이해했는데 1번 사항에 대해 추가로 설명을 해주실 수 있을까요?  <들어가며...> 부분을 각주로 묶는 방법이라는 것이 이해가 잘 가지 않습니다.  

[이해한 변경 요청사항]
1. 단락별로 구분해서 표시하면 좋겠습니다.    <-  **추가설명 부탁드려요 : )**
2. 자바의 싱글턴과 스프링의 싱글턴을 비교하는 내용을 추가했으면 좋겠습니다.

**Comment by mike6321** [comment]
![image](https://user-images.githubusercontent.com/33277588/88012152-2663fd80-cb54-11ea-9f1f-aba0868c12c9.png)

이러한 식으로 도입부를 따로 나누는 것도 좋을 것 같습니다~!!!

**Comment by bbubbush** [comment]
아 이해됐습니다  감사합니다 :>
