### ISSUE TITLE
(이펙티브 자바) 아이템 02. 생성자에 매개변수가 많다면 빌더를 고려하라

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#14]
포스팅 잘 읽었습니다. 읽으면서 보강하면 더 좋을 것을 적어봤으니 검토 부탁드립니다. : )

1. '얼리고' 라는 단어를 freeze()라고 그대로 적는 것이 좋을 것 같습니다. 책을 읽지 않고 본다면 '얼리고'가 무엇을 말하는지 이해하기 어려울 수 있다고 생각합니다. 추가로 EnumSet에 대한 설명처럼 freeze()에 대한 내용을 넣어주면 별도의 참고자료 없이 이해를 도울 수 있습니다.(Javascript의 freeze() 설명 :: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

2. 빌더패턴 단점에 대한 내용이 추가되면 좋겠습니다. 

3. 마지막 단락에 포스팅하면서 배운 점이나 간단히 정리된 내용이 언급되면 학습에 도움을 줄 수 있을 것 같네요.

이상입니다. 👍

**Comment by mike6321** [comment]
유진님 해당 내용에 대해서 피드백 부탁드립니다.

**Comment by SSinsa** [comment]
[피드백 지연 공지] ㅇㅅㅇ?

**Comment by bbubbush** [comment]
반영한 것 같아 해당 이슈는 종료하겠습니다.
모두 고생 많았어요 : )
