### ISSUE TITLE
(이펙티브 자바) 아이템 01. 생성자 대신 정적 팩터리 메서드를 고려하라.

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#15]
포스팅 잘 읽었습니다. 읽으면서 보강하면 더 좋을 것을 적어봤으니 검토 부탁드립니다. : )

1. 구분선이 많아서 읽는 도중에 흐름이 끊기는 느낌입니다. 매끄럽게 글을 읽을 수 있도록 개선할 수 있는 부분이라고 생각합니다.

2. <장점1>의 예제를 책에 있는 BigInteger 생성자 대신 이해하기 쉬운 예제로 변경했으면 좋겠습니다. 
개인적인 생각이지만 책의 BigInteger 예제는 이 객체에 대한 사전지식이 필요하기 때문에 부적절한 예제라고 생각합니다. 따라서 처음 보는 사람도 직관적으로 이해할 수 있는 샘플코드로 변경하면 좋을 것 같습니다.

3. <장점5> 샘플코드의 ‘이놈의~’ 주석은 조금 더 정중한 표현으로 변경 되었으면 싶습니다.

이상입니다. 👍

**Comment by mike6321** [comment]
![image](https://user-images.githubusercontent.com/33277588/88028236-566ec900-cb73-11ea-9cad-feef37529b2a.png)

불편 클래스가 아닌 불변 클래스가 아닌지요.
확인 부탁드립니다.

**Comment by imesung** [comment]
수정 완료했습니다~!
