### ISSUE TITLE
(이펙티브 자바) 아이템 03. private 생성자나 열거타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by mike6321** [FourTeamProject/Charmander_EffectiveJava#16]
용어에 대해서 궁금한 점이 있습니다.
Double Locking Checking 이 아닌 **Double Checked Locking**이 아닌지요~?
확인 부탁 드립니다.

**Comment by bbubbush** [comment]
감사합니다 정신없이 새벽에 쓰다보니 잘못된 용어를 사용했습니다

바로 변경하도록 하겠습니다 : )
