### ISSUE TITLE
[1주차 이슈사항 정리]

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#18]
**1. 다음주 포스팅에는 '리자드'로 이미지 변경** 
 - 해당 이미지는 최준우씨가 공유해주시면 감사하겠습니다. 
   
**2. Static factory method패턴과 Builder패턴의 차이점과 역할의 구분을 무엇으로 봐야하는가?**
 - 임혜성씨와 채유진씨가 정리해주시면 감사하겠습니다.  
  
**3. LazyHolder 방식의 싱글턴 생성의 흐름과 왜 이름이 LazyHolder인지 찾아보기**
 - 제가 담당하여 정리 후 공유하겠습니다.  
  
**4. 인스턴스화를 막기 위해 abstract 키워드를 사용하는 경우, 서브 클래스에서 인스턴스를 생성 후 슈퍼클래스의 기능을 동작하도록 할 수 있는지 확인하는 예제 코드 작성해보기**
 - 최준우씨가 확인 후 과정 및 결과에 대해 다음 수업시간에 간단히 발표해주시기 바랍니다.

---
한 주 고생하셨습니다 ; )

**Comment by mike6321** [comment]
4. 인스턴스화를 막기 위해 abstract 키워드를 사용하는 경우, 서브 클래스에서 인스턴스를 생성 후 슈퍼클래스의 기능을 동작하도록 할 수 있는지 확인하는 예제 코드 작성해보기

해당 내용을 가장 잘 설명해주는 예시가 디자인패턴 중 **팩토리메서드패턴** 이라고 생각합니다.
해당 코드에 대한 예시 코드를 작성 하였으며
수업시간에 발표 하겠습니다.

https://github.com/mike6321/PURE_JAVA/tree/master/EffectiveStudy/src/main/java/me/choi/abstractinstance

**Comment by SSinsa** [comment]
**2. Static factory method패턴과 Builder패턴의 차이점과 역할의 구분을 무엇으로 봐야하는가?**

 팩토리는 단순히 생성자와 관련된 랩퍼 함수이다. 팩토리 매서드 패턴에서는 전체 오브젝트를 위한 한번의 함수 호출이 요구된다. 하나의 라인에 모든 파라미터들이 전달되어야 하며 최종 오브젝트가 리턴될 것이다.
 
 실제 생활에서 예를 찾아보면 레스토랑의 오늘의 식사와 같다. 식사의 생성은 팩토리 패턴이다. 때문에 우리는 주문할때 오늘의 식사를 달라고 하고 이러한 오브젝트는 비밀의 기준에 의해 생성된 식사를 제공한다.

 빌더 패턴은 생성자를 위해 전달가능한 모든 파라미터의 래퍼 오브젝트이다. 여기서는 생성을 위한 파라미터를 전달하기 위한 세터가 허용된다.

 실제 생활에서의 예는 커스텀 피자이다. 이 경우 추가 치즈라던지, 올리브, 옥수수들을 커스터마이징 할 수 있다. 그러므로 필더는 생성될 오브젝트가 가질 수 있는 어트리뷰트들을 노출하고 생성 과정은 감춘다.

출처: https://opennote46.tistory.com/217 [욱'S 노트]

+
https://c10106.tistory.com/4399
이것도 참고

**Comment by bbubbush** [comment]
3. LazyHolder 방식의 싱글턴 생성의 흐름과 왜 이름이 LazyHolder인지 찾아보기

getInstance()를 호출하는 시점에 LazyHolder클래스를 초기화를 한다. 따라서 LazyHolder는 이름 그대로 객체생성을 지연시키는 지지대의 역할을 한다.

https://pokemon-fourteam.tistory.com/6 포스팅에 해당 내용을 추가했습니다.
