### ISSUE TITLE
[3주차 수업일정 공지]

### ISSUE THREAD

**Issue by SSinsa** [FourTeamProject/Charmander_EffectiveJava#23]
[3주차]
일정 : 2020년 8월 04일(화)
정리 및 다음 수업 공지 : 채유진

임혜성 -> 아이템9:: try-finally보다는 try-with-resources를 사용하라
이상훈 -> 아이템10:: equals는 일반 규약을 지켜 재정의하라
채유진 -> 아이템11:: equals를 재정의하려거든 hashCode도 재정의하라
최준우 -> 아이템12:: toString을 항상 재정의하라

[4주차]
일정 : 2020년 8월 11일(화)
정리 및 다음 수업 공지 : 임혜성

**Comment by mike6321** [comment]
3주차 특이사항 없으므로 이슈 클로징하겠습니다.
