### ISSUE TITLE
[4주차 수업일정 공지]

### ISSUE THREAD

**Issue by mike6321** [FourTeamProject/Charmander_EffectiveJava#25]
[4주차]
일정 : 2020년 8월 11일(화)
정리 및 다음 수업 공지 : 최준우

임혜성 -> 아이템13:: clone 재정의는 주의해서 진행하라
 이상훈 -> 아이템14:: Comparable을 구현할지 고려하라
 채유진 -> 아이템15:: 클래스와 멤버의 접근 권한을 최소화하라
 최준우 -> 아이템11:: equals를 재정의하려거든 hashCode도 재정의하라

[5주차] 
일정 : 2020년 8월 18일(화)
 정리 및 다음 수업 공지 : 임혜성

**Comment by bbubbush** [comment]
수업이 종료되어 해당 이슈는 종료하겠습니다.
