### ISSUE TITLE
[5주차 수업일정 공지]

### ISSUE THREAD

**Issue by imesung** [FourTeamProject/Charmander_EffectiveJava#27]
[5주차]
일정 : 2020년 8월 11일(화)
정리 및 수업 공지 : 임혜성

이슈사항
-> 객체 해시 함수에서 31을 사용하는 이유(준우)
-> List의 가변 객체를 두었을 때 clone() 메소드만을 사용하여 전체적인 객체를 복제할 수 있는 방법/1급 객체 참조(혜성)
-> 정보은닉의 종류 3가지(유진)

다음 수업 공지
임혜성 -> 아이템16:: public 클래스에는 public 필드가 아닌 접근자 메서드를 사용하라
이상훈 -> 아이템17:: 변경 가능성을 최소화하라
채유진 -> 아이템18:: 상속보다는 컴포지션을 사용하라
최준우 -> 아이템19:: 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라.

[6주차]
일정 : 2020년 8월 18일(화)
정리 및 다음 수업 공지 : 이상훈

**Comment by bbubbush** [comment]
6주차 수업이 종료되어 해당 이슈는 종료하겠습니다.

모두 이번주도 고생 많았습니다 : )
