### ISSUE TITLE
[7주차 아이템 변경 요청] To bbubbush -> From mike6321

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#30]
[변경 전]
bbubbush :: Item21 인터페이스는 구현하는쪽을 생각해 설계해라
mike6321 :: Item23 태그 달린 클래스보다는 클래스 계층구조를 활용하라

[변경 후]
bbubbush :: Item23 태그 달린 클래스보다는 클래스 계층구조를 활용하라
mike6321 :: Item21 인터페이스는 구현하는쪽을 생각해 설계해라

[변경사유]
태그 달린 클래스라길래 뭘 말하는지 궁금해서 변경을 요청합니다 : )

**Comment by mike6321** [comment]
확인 완료했습니다😄
