### ISSUE TITLE
7월 14일 이슈사항 정리

### ISSUE THREAD

**Issue by imesung** [FourTeamProject/Charmander_EffectiveJava#4]
## **1주차 이슈사항 정리**
1. 한 주당 아이템 4개씩 정리한다.
2. 팀원들은 매주 사전에 정해놓은 아이템을 포스팅한다.
    - 포스팅 시 이미지 첨부(파이리), 레퍼런스(인터파크 책), 소스 링크(깃헙)를 작성한다.
3. 발표자는 아이템 4개를 모두 발표한다. (유진차이는 1개)
4. 매주 발표 담당자가 issue를 정리한다.
5. issue 많이 달아보자!! 모르는 것은 바로바로 issue에!!

**Comment by mike6321** [comment]
다음 발표자 및 일정 까지 이슈 공유해 주시면 감사하겠습니다.

**Comment by bbubbush** [comment]
지난주 이슈 및 일정 공유는 클로즈 하겠습니다.
