### ISSUE TITLE
[Item01] p.11 Service Provider Framework 에 대한 부가설명이 필요합니다.

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/Charmander_EffectiveJava#9]
Service interface, Provider registration API, Service access API   각 역할이 어떻게 흘러가는지 잘 이해가 안가 질문을 남깁니다.

책에서 JDBC를 예시로 드니깐 JDBC를 샘플로 프레임워크의 흐름을 알고 싶습니다.

참고할만한 자료가 있으면 추천해주세요 : )

**Comment by mike6321** [comment]
https://www.youtube.com/watch?v=X7RXP6EI-5E&list=PLfI752FpVCS8e5ACdi5dpwLdlVkn0QgJJ

영상의 40:40 쪽에 해당 부분에 대한 설명이 나옵니다.
참고해주시면 감사하겠습니다.
